[package]
name = "uniproc"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.37.0"
clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
